apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  connection-string: bW9uZ29kYjovL3Byb2plY3QtZGI6T3pjZ2NSejh1RXB0YmU4MHJJcVJYT2dTVzJJVTZCNFAzaHdMQlpiWE5ubjd4QzRtbXhCQWJ3T2xsdkJJMlZKODY1RmZiY0U5YVE0NUFDRGJHTkdxa3c9PUBwcm9qZWN0LWRiLm1vbmdvLmNvc21vcy5henVyZS5jb206MTAyNTUvP3NzbD10cnVlJnJldHJ5d3JpdGVzPWZhbHNlJnJlcGxpY2FTZXQ9Z2xvYmFsZGImbWF4SWRsZVRpbWVNUz0xMjAwMDAmYXBwTmFtZT1AcHJvamVjdC1kYkA=